import assert from "node:assert/strict";
import test from "node:test";
import {
  fetchTedCaptionTracks,
  fetchTedTranscript,
  isTedCaptionUrl,
  isTedManifestUrl,
  parseTedCaptionTracks
} from "../extension/platforms/ted-captions.js";

const manifestUrl = "https://hls.ted.com/project_masters/8560/manifest.m3u8?intro_master_id=9294&preview";
const manifest = `#EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="medium",URI="index-f8-a1.m3u8",LANGUAGE="en"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="en",NAME="English",AUTOSELECT=YES,URI="/project_masters/8560/subtitles/en.m3u8?intro_master_id=9294&preview=true"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",LANGUAGE="zh-cn",NAME="Chinese, Simplified",AUTOSELECT=YES,URI="/project_masters/8560/subtitles/zh-cn.m3u8?intro_master_id=9294&preview=true"`;

test("TED HLS caption tracks are normalized from the master manifest", () => {
  assert.deepEqual(parseTedCaptionTracks(manifest, { videoId: "485565", manifestUrl }), [
    {
      videoId: "485565",
      languageCode: "en",
      label: "English",
      isAutoGenerated: false,
      trackUrl: "https://hls.ted.com/project_masters/8560/subtitles/en/full.vtt?intro_master_id=9294&preview=true"
    },
    {
      videoId: "485565",
      languageCode: "zh-cn",
      label: "Chinese, Simplified",
      isAutoGenerated: false,
      trackUrl: "https://hls.ted.com/project_masters/8560/subtitles/zh-cn/full.vtt?intro_master_id=9294&preview=true"
    }
  ]);
});

test("TED caption and manifest URLs are restricted to the expected HTTPS host and paths", () => {
  assert.equal(isTedManifestUrl(manifestUrl), true);
  assert.equal(isTedCaptionUrl("https://hls.ted.com/project_masters/8560/subtitles/en/full.vtt"), true);
  assert.equal(isTedManifestUrl("https://example.com/project_masters/8560/manifest.m3u8"), false);
  assert.equal(isTedCaptionUrl("https://hls.ted.com/project_masters/8560/manifest.m3u8"), false);
  assert.equal(isTedCaptionUrl("http://hls.ted.com/project_masters/8560/subtitles/en/full.vtt"), false);
});

test("TED caption list and VTT cues are fetched and normalized", async () => {
  const previousFetch = globalThis.fetch;
  globalThis.fetch = async (url, init) => {
    assert.equal(init.redirect, "error");
    if (url === manifestUrl) {
      return new Response(manifest, { status: 200 });
    }
    assert.equal(url, "https://hls.ted.com/project_masters/8560/subtitles/en/full.vtt?intro_master_id=9294&preview=true");
    return new Response(`WEBVTT\n\n00:00:04.376 --> 00:00:08.046\nMy wife grew up in Santa Rosa, California,\n`, {
      status: 200,
      headers: { "Content-Type": "text/vtt" }
    });
  };

  try {
    const tracks = await fetchTedCaptionTracks({ videoId: "485565", manifestUrl });
    assert.equal(tracks.length, 2);
    const document = await fetchTedTranscript({
      videoId: "485565",
      sourceLanguage: tracks[0].languageCode,
      trackUrl: tracks[0].trackUrl
    });
    assert.deepEqual(document, {
      platform: "ted",
      videoId: "485565",
      sourceLanguage: "en",
      cues: [{
        id: "ted-0",
        start: 4.376,
        end: 8.046,
        text: "My wife grew up in Santa Rosa, California,"
      }]
    });
  } finally {
    globalThis.fetch = previousFetch;
  }
});

test("TED rejects manifests without subtitle tracks", async () => {
  const previousFetch = globalThis.fetch;
  globalThis.fetch = async () => new Response("#EXTM3U\n#EXT-X-VERSION:4\n", { status: 200 });
  try {
    await assert.rejects(
      fetchTedCaptionTracks({ videoId: "485565", manifestUrl }),
      /No TED captions are available/
    );
  } finally {
    globalThis.fetch = previousFetch;
  }
});
